name: Test Runner

on:
 push:
  branches:
  - main

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code 
      uses: actions/checkout@v3

    - name: setup 
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x' 

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test
    
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    
      with:
          name: TestReport          
          path: report.html    
          reporter: jest-junit